version: '3'
services:
  #PHP Service
  fruit_app:
    build:
      context: .
      dockerfile: app.docker
    container_name: fruit_app
    volumes:
      - ../:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - fruit_mysql:db

  #Nginx Service
  fruit_web:
    image: nginx:1.21.1
    container_name: fruit_web
    ports:
      - 8089:89
    volumes:
      - ../:/var/www
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fruit_app

  # MySQL Service
  fruit_mysql:
    image: mysql:8
    container_name: fruit_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: fruit
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - fruit-mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
#Docker Networks
volumes:
  fruit-mysql: {}
